import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
import React from "react";

const Home: NextPage = () => {
  const price = 30;
  const [quantity, setQuantity] = React.useState(1);
  const [total, setTotal] = React.useState(price);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dowell Tipdowns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          className="absolute top-0 w-full h-1/3 lg:h-full lg:w-1/3 lg:left-0"
          style={{ background: "#CCD5AE" }}
        ></div>
        {/* <h1 className={styles.title}>DOWELL TIP DOWN</h1> */}
        <div
          className="flex flex-col items-center lg:flex-row"
          style={{ zIndex: 1 }}
        >
          <img
            className="w-56 shadow-md rounded-md mt-8 lg:basis-1/3 lg:ml-20 lg:mt-0"
            src="/logo.jpg"
          />
          <div className="flex flex-col items-center mt-6 lg:basis-1/3 lg:m-auto">
            <div>
              DoWell Tip Downs are made of red oak and I use stainless stell
              hardware for a long lasting product. Comes with base, fishing
              pole, hook and split shot. Everything but the Minnow!
            </div>
            <div className="my-6">
              Where Tip Downs shine:
              <br />
              <br />
              Why do you need a Tip Down?!? Tip Downs catch even the most
              negative fish. With its design, the fish doesn't feel any
              resistance after it takes the minnow in its mouth. Tip downs are
              fantastic for catching crappie, perch and even bass and pike! Hold
              when a pike bites, it's a pretty fun reeling in a pike on a rod
              like this.
            </div>
            <h2 className="mb-4">${total}</h2>
            <div className="mb-4 flex items-center">
              <button
                className="h-10 w-10"
                style={{ background: "#E9EDC9" }}
                onClick={() => {
                  if (quantity <= 1) return;
                  const newQuantity = quantity - 1;
                  setQuantity(newQuantity);
                  setTotal(price * newQuantity);
                }}
              >
                {" "}
                -{" "}
              </button>
              <div className="mx-4">{quantity}</div>
              <button
                className="h-10 w-10"
                style={{ background: "#E9EDC9" }}
                onClick={() => {
                  const newQuantity = quantity + 1;
                  setQuantity(newQuantity);
                  setTotal(price * newQuantity);
                }}
              >
                {" "}
                +{" "}
              </button>
            </div>
            <PayPalScriptProvider options={{ "client-id": "test" }}>
              <PayPalButtons style={{ layout: "horizontal" }} />
            </PayPalScriptProvider>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
